### ISSUE TITLE
Run CLR benchmarks using 64-bit.

### ISSUE THREAD

**Issue by OniBait** [biboudis/clashofthelambdas#2]
There is a fairly significant improvement to the C# (and presumably F#) benchmarks on Windows if you force x64:
`csc /platform:x64`

Would also be interesting to test it with the upcoming RyuJIT CLR.

**Comment by palladin** [comment]
Hi OniBait,
Thanks for the suggestion. Yes I completely agree that it's very interesting to run our tests with the upcoming RyuJIT CLR. Feel free to share with us your own perf results.

**Comment by OniBait** [comment]
Gist w/ RyuJIT included:
https://gist.github.com/OniBait/5d5a6d5e4adaec979db1

Should also point out that in the CLR cases, you are really measuring IEnumerable differences (seeing as how one could easily write an extension method handling Arrays instead and see the "optimized" results. Which is fine I guess, but isn't a "clash of the lamdas" is more "clash of the build in iterators". (looks like the same goes for the Scala impl)

**Comment by palladin** [comment]
Thanks for sharing with us your benchmarks. The problem with Arrays and other strict collections is that they are not memory efficient by definition (temporary intermediate collections). 
array |> Array.map (fun ...) |> Array.map (fun ...) |> Array.sum
The composable solution is to use Streaming (or non-strict/lazy collections) and in our work we evaluated the combined cost of lambdas and stream APIs. 
A more accurate title could be "Clash of the Streaming Lambdas" :)
